# Generated by Django 3.2.3 on 2021-11-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usertags'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertags',
            name='Bio',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
