# Generated by Django 3.2.3 on 2021-11-07 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usertags_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertags',
            name='Bio',
        ),
    ]
