# Generated by Django 3.2.8 on 2021-11-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211110_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertags',
            name='profile_image',
            field=models.ImageField(upload_to='static/images/%y'),
        ),
        migrations.AlterField(
            model_name='usertags',
            name='status',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
