# Generated by Django 3.2.8 on 2021-10-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogdb_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdb',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blogdb',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
