# Generated by Django 3.2.8 on 2021-10-25 12:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_post_blogcomment_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdb',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogdb',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
