# Generated by Django 3.2.8 on 2021-11-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogdb_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdb',
            name='tags',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
