# Generated by Django 3.2.3 on 2021-11-10 07:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_blogdb_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdb',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='bdislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogdb',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='blikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
