# Generated by Django 3.2.8 on 2021-11-15 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211110_2149'),
        ('blog', '0012_blogcomment_userimageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='userImageUrl',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='usertags',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.usertags'),
            preserve_default=False,
        ),
    ]
